---
title: "01 Data Prep"
author: "JungHwan Yang"
date: "March 26, 2015"
output: html_document
---

## This is Korean Presidential Debate 1 project.

To read the data without formatting errors, I had to read the text file in SPSS and saved in .sav; then read it from R.

```{r Read raw data}
path <- "Data//koprez1.sav"
d <- read.spss(path, use.value.labels = F, to.data.frame = T)

d[d == "\\N"] <- NA

# For quick transformation of df, convert the df into data table
library(data.table)
d.table <- data.table(d)
# Sort by time
setorder(d.table, V2)
d.table <- subset(d.table, V2 != "NA")
# Subset two hours (2:20 hours)
d2 <- subset(d.table,
               as.POSIXct(V2) > '2012-12-04 10:30:00' &
               as.POSIXct(V2) < '2012-12-04 13:30:00')
rm(d);rm(d.table)
```

http://rstudio-pubs-static.s3.amazonaws.com/1617_b9a9f37daa2d48d9be83ad0b91d7fdf4.html

http://www.ddokbaro.com/3695


```{r}
library(KoNLP)
library(tm)

removeRT <- function(x) {
    gsub("RT @[[:graph:]]*", "", x)
}

removeTwit <- function(x) {
    gsub("@[[:graph:]]*", "", x)
}

removeURL <- function(x) {
    gsub("http://[[:graph:]]*", "", x)
}

d2$text <- sapply(d2$V3, removeRT)
d2$text <- sapply(d2$text, removeTwit)
d2$text <- sapply(d2$text, removeURL)
useSejongDic()

d2$text <- sapply(d2$text, function(x) {
  paste(extractNoun(x), collapse = " ")
  })
```
